services:
  db:
    image: postgres:14.10
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    web:
    build: .
    container_name: django
    # Remove the 'command' line to use the Dockerfile CMD
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "127.0.0.1:8000:8000"  # Only expose to localhost
    env_file:
      - .env
    depends_on:
      - db
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
